// The Lost Jamaican store catalog.
// Every merch SKU here is validated against live marketplace sales data
// (Etsy review counts, Amazon "bought in past month", competitor pricing) —
// see docs/store-research.md. No unproven items ship in a drop.

export const STORE_BRAND = {
  name: 'The Lost Jamaican',
  tagline: 'Wear the culture. Learn the craft.',
};

// status: 'soon' = shown, email-notify only (no checkout until Printify products exist)
//         'live' = purchasable
export const MERCH = [
  {
    id: 'not-perfect-mug',
    type: 'mug',
    name: '"Not Perfect, But Jamaican" Mug',
    phrase: "I'm not perfect but I am Jamaican and that's close enough",
    colorway: 'Two-tone flag letters',
    price: 1899,
    image: '/store/not-perfect-mug.jpg',
    status: 'soon',
  },
  {
    id: 'not-perfect-tee',
    type: 'tee',
    name: '"Not Perfect, But Jamaican" Tee',
    phrase: "I'm not perfect but I am Jamaican and that's close enough",
    colorway: 'Black · gold type',
    price: 2799,
    image: '/store/not-perfect-tee.jpg',
    status: 'soon',
  },
  {
    id: 'bomboclaat-mug',
    type: 'mug',
    name: 'Bomboclaat — Dictionary Mug',
    phrase: 'bom·bo·claat — exclamation of surprise',
    colorway: 'White · black serif',
    price: 1899,
    image: '/store/bomboclaat-mug.jpg',
    status: 'soon',
  },
  {
    id: 'lost-found-mug',
    type: 'mug',
    name: '"Lost in America, Found in Jamaica" Mug',
    phrase: 'Lost in America. Found in Jamaica.',
    colorway: 'US / JA flag split',
    price: 1899,
    image: '/store/lost-found-mug.jpg',
    status: 'soon',
  },
  {
    id: 'wah-gwaan-tee',
    type: 'tee',
    name: 'Wah Gwaan Tee',
    phrase: 'Wah Gwaan',
    colorway: 'Black · distressed retro',
    price: 2799,
    image: '/store/wah-gwaan-tee.jpg',
    status: 'soon',
  },
  {
    id: 'retro-flag-tee',
    type: 'tee',
    name: 'Retro Watercolor Jamaica Tee',
    phrase: 'Jamaica',
    colorway: 'Dark heather · vintage watercolor flag',
    price: 2699,
    image: '/store/retro-flag-tee.jpg',
    status: 'soon',
  },
  {
    id: 'believe-mug',
    type: 'mug',
    name: '"Believe Inna Yuhself" Mug',
    phrase: 'Believe inna yuhself',
    colorway: 'Black · green & gold',
    price: 1999,
    image: '/store/believe-mug.jpg',
    status: 'soon',
  },
  {
    id: 'dictionary-tee',
    type: 'tee',
    name: 'Patois Dictionary Series Tee',
    phrase: 'Cho! · Rhaatid · Soon Come',
    colorway: 'White · minimal type',
    price: 2799,
    image: '/store/dictionary-tee.jpg',
    status: 'soon',
  },
  {
    id: 'area-code-tee',
    type: 'tee',
    name: '876 Tee',
    phrase: '876',
    colorway: 'Black · gold numerals',
    price: 2799,
    image: '/store/area-code-tee.jpg',
    status: 'soon',
  },
  {
    id: 'never-lose-tee',
    type: 'tee',
    name: 'NEVER LOSE Tee',
    phrase: 'NEVER LOSE',
    colorway: 'Black · bold white block',
    price: 2999,
    image: '/store/never-lose-tee.jpg',
    flagship: true,
    status: 'soon',
  },
  {
    id: 'more-money-mug',
    type: 'mug',
    name: 'MORE MONEY THAN LAST YEAR Mug',
    phrase: 'More money than last year',
    colorway: 'Black · gold type',
    price: 1999,
    image: '/store/more-money-mug.jpg',
    flagship: true,
    status: 'soon',
  },
  {
    id: 'cant-hear-poster',
    type: 'poster',
    name: '"Who Can\'t Hear Will Feel" Poster',
    phrase: "Who can't hear will feel",
    colorway: 'Minimal typography · 18×24',
    price: 1999,
    image: '/store/cant-hear-poster.jpg',
    status: 'soon',
  },
];

export const COURSES = [
  {
    id: 'course-free',
    name: 'The Free Mini-Lesson',
    price: 0,
    priceLabel: 'Free',
    blurb: 'How one name becomes a finished cinematic vertical video — the full pipeline explained in one lesson.',
    features: ['The 10-step pipeline overview', 'The tools list (all of it)', 'One real script, annotated'],
    status: 'soon',
  },
  {
    id: 'course-starter',
    name: 'Starter — Script & Prompts',
    price: 999,
    priceLabel: '$9.99',
    blurb: 'Write scripts that hold attention and prompts that hold a face. The writing half of the system.',
    features: ['Script structure & hooks', 'The prompt workflow', 'Character consistency basics', 'A prompt pack included'],
    status: 'soon',
  },
  {
    id: 'course-pipeline',
    name: 'The Full Pipeline',
    price: 1999,
    priceLabel: '$19.99',
    blurb: 'The entire system, end to end — research to render to publish. Everything we use, nothing held back.',
    features: ['Every production step, on video', 'Model settings & QC gates', 'The automation scripts', 'All prompt packs bundled', 'Lifetime updates'],
    flagship: true,
    status: 'soon',
  },
];

export const merchById = (id) => MERCH.find((m) => m.id === id);
